import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Candidate {
    displayName: string;
    voteCount: number;
    percentage: number;
}

interface ElectionResultsData {
    title: string;
    positionName: string;
    endTime: string;
    totalVotes: number;
    candidates: Candidate[];
}

export function exportElectionResultsToPDF(data: ElectionResultsData) {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(33, 33, 33);
    doc.text('TrueChoice Election Results', pageWidth / 2, 20, { align: 'center' });

    // Election title
    doc.setFontSize(16);
    doc.setTextColor(66, 66, 66);
    doc.text(data.title, pageWidth / 2, 32, { align: 'center' });

    // Position
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Position: ${data.positionName}`, pageWidth / 2, 40, { align: 'center' });

    // Date and total votes
    doc.setFontSize(10);
    doc.text(`Election Ended: ${new Date(data.endTime).toLocaleString()}`, 14, 55);
    doc.text(`Total Votes Cast: ${data.totalVotes}`, 14, 62);

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 68, pageWidth - 14, 68);

    // Winner section
    if (data.candidates.length > 0) {
        const winner = data.candidates[0];
        doc.setFontSize(14);
        doc.setTextColor(34, 139, 34); // Green
        doc.text('WINNER', 14, 80);

        doc.setFontSize(16);
        doc.setTextColor(33, 33, 33);
        doc.text(winner.displayName, 14, 90);

        doc.setFontSize(12);
        doc.setTextColor(66, 66, 66);
        doc.text(`${winner.voteCount} votes (${winner.percentage}%)`, 14, 98);
    }

    // Results table
    doc.setFontSize(14);
    doc.setTextColor(33, 33, 33);
    doc.text('All Results', 14, 115);

    const tableData = data.candidates.map((c, index) => [
        index + 1,
        c.displayName,
        c.voteCount,
        `${c.percentage}%`
    ]);

    autoTable(doc, {
        startY: 120,
        head: [['Rank', 'Candidate', 'Votes', 'Percentage']],
        body: tableData,
        theme: 'striped',
        headStyles: {
            fillColor: [59, 130, 246], // Blue
            textColor: 255,
            fontStyle: 'bold'
        },
        alternateRowStyles: {
            fillColor: [245, 245, 245]
        },
        styles: {
            cellPadding: 4,
            fontSize: 10
        }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
        `Generated by TrueChoice on ${new Date().toLocaleString()}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
    );

    // Save the PDF
    const filename = `${data.title.replace(/[^a-zA-Z0-9]/g, '_')}_results.pdf`;
    doc.save(filename);

    return filename;
}
